# Generated by Django 4.2 on 2023-04-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_url',
            field=models.URLField(null=True),
        ),
    ]
