# Generated by Django 4.2 on 2023-04-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_ideas', '0002_alter_idea_idea_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
